adding first tests for payment - market place
StuDocu/playwright-tests-sandbox pull request #11
Opened 2022-10-05 14:29 UTC by studocuvitor

I am renaming my branch so it follows the standards.

2022-10-13 08:22 UTC, danielcastro-studocu requested changes

2022-10-13 08:22 UTC, danielcastro-studocu commented on pages/payment.ts
> +        await frameCardInput.fill('4293189100000008');
Maybe if you use `fillInInput` method from helpers which is imported here but not used you can inform `{timeout: 2000}` as an option, avoiding the explicit wait above.

2022-10-13 08:22 UTC, danielcastro-studocu commented on pages/payment.ts
> +        await frameCardInput.click();
I see that for some click actions above you are using `clickOnElement`. What if we use it by default?

2022-10-13 08:22 UTC, danielcastro-studocu commented on tests/payments.spec.ts
> +    await payment_page.waitForPaymentPage(page);
As suggested in the payment page, this wait should be moved to `chooseYourPlan`.

2022-10-20 09:08 UTC, mila-qa commented on tests/payments.spec.ts
> +test('user pays premium with credit card', async ({page, isMobile}) => {
is this test about starting trial payment for a quarter subscription? Would be nice to know which Gherkin scenario is transformed here.

Mine test user is from TU Delft( phase 4 university). It was navigated to a trial payment page after clicking on upgrade button.

2022-10-20 09:08 UTC, mila-qa commented on tests/payments.spec.ts
> +    await payment_page.insertYourCreditCardData(page);
Test looks unfinished. User submitted payment data and what should happen after that? 
Could you please add assertion(s) to highlight that purpose of the test is achieved

2022-11-08 15:51 UTC, studocuvitor commented on pages/home.ts
> +const upgradeBtn = 'premium-badge-without-circle-icon';
Done.

2022-11-08 15:51 UTC, studocuvitor commented on pages/home.ts
> +const clickUpgradeButton = async (page: Page) => {
Done.

2022-11-08 15:51 UTC, studocuvitor commented on pages/payment.ts
> +const waitForPaymentPage = async (page: Page) => {
Done.

2022-11-08 15:52 UTC, studocuvitor commented on pages/payment.ts
> +    }if(planType=='Annual'){
Done.

2022-11-08 15:52 UTC, studocuvitor commented on pages/payment.ts
> +const chooseYourPlan = async(page: Page, planType: string) => {
Done.

2022-11-08 15:52 UTC, studocuvitor commented on pages/payment.ts
> +        await page.waitForTimeout(2500);
Done. Removed explicit wait as `chooseYourPaymentMethod` has a `waitForVisible` already.

2022-11-08 15:52 UTC, studocuvitor commented on pages/payment.ts
> +    if(paymentMethod=='Cards'){
Because in the future we will implement other types of payment i.e. iDeal, DANA, MoMo, GCash, GooglePay...

2022-11-08 15:53 UTC, studocuvitor commented on pages/payment.ts
> +        await frameCardInput.fill('4293189100000008');
When using fillInInput for frames we got below error:

```
page.click: DOMException: Failed to execute 'querySelectorAll' on 'Document': '[data-test-selector="Locator@//*[@data-cse="encryptedExpiryDate"]//iframe >> control=enter-frame >> //input[@data-fieldtype='encryptedExpiryDate']"]' is not a valid selector.

        at query (<anonymous>:3112:41)
        at <anonymous>:3122:7
        at SelectorEvaluatorImpl._cached (<anonymous>:2910:20)
        at SelectorEvaluatorImpl._queryCSS (<anonymous>:3109:17)
        at SelectorEvaluatorImpl._querySimple (<anonymous>:2986:19)
        at <anonymous>:2944:29
        at SelectorEvaluatorImpl._cached (<anonymous>:2910:20)
        at SelectorEvaluatorImpl.query (<anonymous>:2939:19)
        at Object.query (<anonymous>:3144:44)
        at <anonymous>:3102:21
    =========================== logs ===========================
    waiting for selector "[data-test-selector="Locator@//*[@data-cse="encryptedExpiryDate"]//iframe >> control=enter-frame >> //input[@data-fieldtype='encryptedExpiryDate']"]"
      Failed to execute 'querySelectorAll' on 'Document': '[data-test-selector="Locator@//*[@data-cse="encryptedExpiryDate"]//iframe >> control=enter-frame >> //input[@data-fieldtype='encryptedExpiryDate']"]' is not a valid selector.
    ============================================================
        at clickOnElement (file:///Volumes/Dev/playwright-tests-sandbox/framework/helpers/utils.ts:22:16)
        at Module.insertYourCreditCardData (file:///Volumes/Dev/playwright-tests-sandbox/framework/pages/payment.ts:53:15)
        at file:///Volumes/Dev/playwright-tests-sandbox/tests/payments.spec.ts:20:5
```

2022-11-08 15:53 UTC, studocuvitor commented on pages/payment.ts
> +        await frameCardInput.click();
When using clickOnElement for frames we got below error:

```
page.click: DOMException: Failed to execute 'querySelectorAll' on 'Document': '[data-test-selector="Locator@//*[@data-cse="encryptedExpiryDate"]//iframe >> control=enter-frame >> //input[@data-fieldtype='encryptedExpiryDate']"]' is not a valid selector.

        at query (<anonymous>:3112:41)
        at <anonymous>:3122:7
        at SelectorEvaluatorImpl._cached (<anonymous>:2910:20)
        at SelectorEvaluatorImpl._queryCSS (<anonymous>:3109:17)
        at SelectorEvaluatorImpl._querySimple (<anonymous>:2986:19)
        at <anonymous>:2944:29
        at SelectorEvaluatorImpl._cached (<anonymous>:2910:20)
        at SelectorEvaluatorImpl.query (<anonymous>:2939:19)
        at Object.query (<anonymous>:3144:44)
        at <anonymous>:3102:21
    =========================== logs ===========================
    waiting for selector "[data-test-selector="Locator@//*[@data-cse="encryptedExpiryDate"]//iframe >> control=enter-frame >> //input[@data-fieldtype='encryptedExpiryDate']"]"
      Failed to execute 'querySelectorAll' on 'Document': '[data-test-selector="Locator@//*[@data-cse="encryptedExpiryDate"]//iframe >> control=enter-frame >> //input[@data-fieldtype='encryptedExpiryDate']"]' is not a valid selector.
    ============================================================
        at clickOnElement (file:///Volumes/Dev/playwright-tests-sandbox/framework/helpers/utils.ts:22:16)
        at Module.insertYourCreditCardData (file:///Volumes/Dev/playwright-tests-sandbox/framework/pages/payment.ts:53:15)
        at file:///Volumes/Dev/playwright-tests-sandbox/tests/payments.spec.ts:20:5
```

2022-11-08 15:53 UTC, studocuvitor commented on tests/payments.spec.ts
> +    await payment_page.waitForPaymentPage(page);
Done.

2022-11-08 15:53 UTC, studocuvitor commented on tests/payments.spec.ts
> +test('user pays premium with credit card', async ({page, isMobile}) => {
Done. Test name updated with correspondent test from Gherkin "Pay premium with the MasterCard credit card"

2022-11-09 17:51 UTC, studocuvitor commented on tests/payments.spec.ts
> +    await payment_page.insertYourCreditCardData(page);
Done.

2022-11-10 15:00 UTC, danielcastro-studocu approved these changes

2022-11-10 15:34 UTC, prachistudocu approved these changes

2022-11-10 15:58 UTC, merged