User Magnet - SEO Tag Features
StuDocu/playwright-tests-sandbox pull request #12
Opened 2022-10-06 14:10 UTC by sharayusakri

SEO Gherkin features
1. seo hrefs on paginated pages
2. nofollow footer links to jobs and help
3. add link to studeersnel on studocu domain

2022-10-21 12:21 UTC, mila-qa requested changes

2022-10-21 12:21 UTC, mila-qa commented on tests/seo.spec.ts
> +    await waitForVisible(page, 'the-cookie-banner');
Visibility of cookie banner is an extra here. `openLandingPage()` waits for banner to be visible

2022-10-21 12:21 UTC, mila-qa commented on framework/pages/landing.ts
> +    const value = await page.locator(jobs).getAttribute("rel");
Could you name function, so it becomes clear that it's not only about navigation, but also about checking attributes. 
For ` navigateToJobsLink` it's enough to `scrollIntoView`

2022-10-21 12:21 UTC, mila-qa commented on tests/seo.spec.ts
> +test('validate studeersnel link in the footer', async ({ page }) => {
what function in this tests validates studeersnel link in the footer?

2022-10-25 13:24 UTC, sharayusakri commented on framework/pages/books.ts
> + */
Removed the comments

2022-10-25 13:24 UTC, sharayusakri commented on framework/pages/landing.ts
> +const institutionsIcon = "svg[data-test-selector='landing-university-icon']";
I had to locate a group of elements, where all the elements had different locators. To combine everything together I have used this style for locating the blocks so that i can check on count -- as the scenario I have is to check if the elements are present or not.

2022-10-25 13:24 UTC, sharayusakri commented on tests/seo.spec.ts
> +import * as home_page from '../framework/pages/landing.ts';
Updated.

2022-10-25 13:24 UTC, sharayusakri commented on tests/seo.spec.ts
> +    await waitForVisible(page, 'the-cookie-banner');
Updated waitForVisible with submitCookieBanner

2022-10-25 13:24 UTC, sharayusakri commented on framework/pages/landing.ts
> +    const value = await page.locator(jobs).getAttribute("rel");
Updated the names of all functions in much more detail

2022-10-25 13:24 UTC, sharayusakri commented on framework/pages/landing.ts
> +const navigateToJobsLink = async (page: Page) => {
Created a separate page [footer.ts] in pages and updated it with related functions.

2022-10-25 13:25 UTC, sharayusakri commented on framework/pages/landing.ts
> +    await page.waitForTimeout(2500);
The test was failing in my local, might be network issue. Removed the wait and ran and is running as expected. Updated the script without waits wherever not required.

2022-10-25 13:25 UTC, sharayusakri commented on tests/seo.spec.ts
> +test('validate studeersnel link in the footer', async ({ page }) => {
validateLinkInFooter function validates if the link is present in the footer

2022-10-25 13:38 UTC, sharayusakri commented on framework/pages/books.ts
> +    console.log(countValue);
Removed the debug info where I printed values, but left the debug Info where I printed Navigation details for tracking purpose during failures

2022-11-07 17:28 UTC, danielcastro-studocu requested changes
I think that the binary `.DS_Store` should not be pushed.

2022-11-07 17:28 UTC, danielcastro-studocu commented on framework/pages/institutions.ts
> +        expect(countValue, "For region ' +region ' and ' +object ' page").toEqual(0);
What’s the purpose of the strings in the `expect` assertion?

2022-11-07 17:28 UTC, danielcastro-studocu commented on framework/pages/landing.ts
> +    const currentURL = url;
it’s not used, so can be removed.

2022-11-07 17:28 UTC, danielcastro-studocu commented on framework/pages/login.ts
> +const url = baseURL + local;
It could be `process.env.BASE_URL + process.env.BASE_LOCALIZATION`

2022-11-07 17:28 UTC, danielcastro-studocu commented on framework/pages/login.ts
> +const clickloginButton = async (page: Page, isMobile) => {
In recent merges it was moved to `/framework/pages/header.ts`.

2022-11-07 17:28 UTC, danielcastro-studocu commented on framework/pages/login.ts
>  const loginWithEmail = async (page: Page, userName: string, userPwd: string) => {
In recent merges it was moved to `/framework/pages/authentication-modal.ts`.

2022-11-07 17:28 UTC, danielcastro-studocu commented on framework/pages/footer.ts
> +const footerLink = "//footer//a[@href='https://www.studeersnel.nl']";
It could be renamed to `dutchWebsiteFooterLink`. WDYT?

2022-11-07 17:28 UTC, danielcastro-studocu commented on framework/pages/footer.ts
> +const jobs = '//*[text()="Jobs"]';
It could be renamed to `jobsFooterLink`. WDYT?

2022-11-09 13:38 UTC, mila-qa reviewed
Sharayu, could you please pull(re-base) main branch into yours? It's ahead of yours. 

Not all tests are passing with this state of branch:
![image](https://user-images.githubusercontent.com/62964414/200844483-556bfddd-c993-4c7f-b5af-7e3703ff06b3.png)
Please make them work again :pray:

2022-11-09 13:38 UTC, mila-qa commented on tests/seo.spec.ts
> +    await cookie_page.submitCookieBanner(page);
we don't need a separate step for the cookie banner as it's already in `openLandingPage(page);`

2022-11-09 13:38 UTC, mila-qa commented on tests/seo.spec.ts
> +        await cookie_page.submitCookieBanner(page);
here as well feel free to remove this line, because it's a duplication

2022-11-09 13:38 UTC, mila-qa commented on tests/seo.spec.ts
> +    await cookie_page.submitCookieBanner(page);
```suggestion

```

2022-11-09 13:38 UTC, mila-qa commented on playwright.config.ts
> +            viewport:  {width: 1500, height: 980 },
any reason to move a viewport option here?

2022-11-09 13:38 UTC, mila-qa commented on playwright.config.ts
> +import {chromium, devices, type PlaywrightTestConfig} from "@playwright/test";
i think it's not necessary to add `chromium` here

2022-11-09 13:38 UTC, mila-qa commented on framework/pages/footer.ts
> +const footerLink = "//footer//a[@href='https://www.studeersnel.nl']";
could you please clean up locators? They should look much simpler. Also, we can add in `utils.ts` every repetitive job to work with locators. For example, getting an attribute:

`const getAttribute = async function (page: Page, dataTestSelector: string, attributeName: string ) {
    return page.locator('[data-test-selector="' + dataTestSelector + '"]').getAttribute(attributeName);
}`


```suggestion
const jobs = 'jobs-link';
...

```
and similar to this template. You can take a look at other pages as example

2022-11-09 13:38 UTC, mila-qa commented on framework/pages/footer.ts
> +    console.log("navigated to social");
those 2 lines can be removed as test isn't interacting with any elelments. And DOM is ready, when page is loaded

2022-11-09 13:38 UTC, mila-qa commented on framework/pages/footer.ts
> +        expect(attributeValue, "For Apps Link ").toContain("nofollow");
looks like an overcomplicated solution to check 2 elements.
My suggestion would be to keep it simple. It'll allow easier to maintain and read tests. For example

```
    const aplleLinkAttribute = await getAttribute(page, appleStoreLink, 'rel');
    const googleLinkAttribute = await getAttribute(page, googlePlayLink, 'rel')
    expect(aplleLinkAttribute).toContain('nofollow');
    expect(googleLinkAttribute).toContain('nofollow');
```

where apple store and google play link can be defined as constants at the toip of this file

```
const appleStoreLink = 'apple-store-link';
const googlePlayLink = 'google-play-link'

```

2022-11-11 09:34 UTC, sharayusakri commented on framework/pages/footer.ts
> +    expect(value, "For Jobs Link ").toContain("nofollow");
I have written that for logging purpose, when any test fails, the message would be clear.

2022-11-11 09:34 UTC, sharayusakri commented on framework/pages/footer.ts
> +        if (!(name == "Blog")) {
Removed the condition and added a new function as the locators changed in rebranded, It was different in legacy

2022-11-11 09:34 UTC, sharayusakri commented on framework/pages/footer.ts
> +            expect(attributeValue, "For Social Link " + name).toContain("nofollow");
Removed this line, as the name does not exist in rebranded

2022-11-11 09:34 UTC, sharayusakri commented on framework/pages/footer.ts
> +        expect(attributeValue, "For Apps Link ").toContain("nofollow");
I have written that for logging purpose, when any test fails, the message would be clear.

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/footer.ts
> +    expect(countValue, "Validating Link in the Footer").toBeGreaterThanOrEqual(1);
I have written that for logging purpose, when any test fails, the message would be clear.

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/books.ts
> +        expect(countValue, "For region ' +region ' and ' +object ' page").toEqual(0);
I have written that for logging purpose, when any test fails, the message would be clear for which region and which page the test failed

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/books.ts
> +        expect(countValue, "For region ' +region ' and ' +object ' page").toBeGreaterThanOrEqual(1);
I have written that for logging purpose, when any test fails, the message would be clear for which region and which page the test failed

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/institutions.ts
> +        expect(countValue, "For region ' +region ' and ' +object ' page").toEqual(0);
I have written that for logging purpose, when any test fails, the message would be clear for which region and which page the test failed

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/landing.ts
> +    const currentURL = url;
fixed

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/login.ts
> +const url = baseURL + local;
updated according to main

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/login.ts
> +const clickloginButton = async (page: Page, isMobile) => {
fixed

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/login.ts
>  const loginWithEmail = async (page: Page, userName: string, userPwd: string) => {
fixed

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/footer.ts
> +const footerLink = "//footer//a[@href='https://www.studeersnel.nl']";
updated

2022-11-11 09:35 UTC, sharayusakri commented on framework/pages/footer.ts
> +const jobs = '//*[text()="Jobs"]';
updated

2022-11-11 09:36 UTC, sharayusakri commented
> Sharayu, could you please pull(re-base) main branch into yours? It's ahead of yours.
> 
> Not all tests are passing with this state of branch: ![image](https://user-images.githubusercontent.com/62964414/200844483-556bfddd-c993-4c7f-b5af-7e3703ff06b3.png) Please make them work again 🙏

Fixed!! 
<img width="985" alt="Screenshot 2022-11-11 at 10 36 39" src="https://user-images.githubusercontent.com/114140941/201311505-32a11bd1-0d61-4815-ad60-df99621d7a44.png">

2022-11-11 09:41 UTC, sharayusakri commented on tests/seo.spec.ts
> +const userPwd = process.env.PASSWORD;
fixed

2022-11-11 11:20 UTC, sharayusakri commented on framework/pages/landing.ts
> +const institutionsIcon = "svg[data-test-selector='landing-university-icon']";
Added new util function as discussed to support new type of locator

2022-11-11 11:20 UTC, sharayusakri commented on tests/seo.spec.ts
> +        await cookie_page.submitCookieBanner(page);
unchanged, as Landing page doesn't have cookie banner as discussed.

2022-11-11 11:20 UTC, sharayusakri commented on tests/seo.spec.ts
> +    await cookie_page.submitCookieBanner(page);
unchanged, as Landing page doesn't have cookie banner as discussed.

2022-11-11 11:21 UTC, sharayusakri commented on playwright.config.ts
> +            viewport:  {width: 1500, height: 980 },
Updated as global instead of specific browser

2022-11-11 11:21 UTC, sharayusakri commented on framework/pages/footer.ts
> +const footerLink = "//footer//a[@href='https://www.studeersnel.nl']";
updated

2022-11-11 11:21 UTC, sharayusakri commented on framework/pages/footer.ts
> +        expect(attributeValue, "For Apps Link ").toContain("nofollow");
updated

2022-11-11 11:22 UTC, sharayusakri commented on tests/seo.spec.ts
> +    await cookie_page.submitCookieBanner(page);
unchanged, as Landing page doesn't have cookie banner as discussed.

2022-11-11 11:23 UTC, sharayusakri commented on playwright.config.ts
> +import {chromium, devices, type PlaywrightTestConfig} from "@playwright/test";
updated

2022-11-22 13:07 UTC, studocuvitor approved these changes
Ok.

2022-11-24 06:57 UTC, danielcastro-studocu approved these changes

2022-11-24 09:04 UTC, merged