Refactoring uploader, adding run script and fixing login for mobile.
StuDocu/playwright-tests-sandbox pull request #3
Opened 2022-08-23 09:33 UTC by danielcastro-studocu

2022-08-24 09:49 UTC, mila-qa requested changes

2022-08-24 09:49 UTC, mila-qa commented on .env
> +USERNAME=user@loc.com
we will need many different users with different roles, state etc. I'm doubt we should put all of them in env file. The same applies to file

2022-08-24 09:49 UTC, mila-qa commented on pages/home.ts
> +    if(isMobile){
isMobile flag is `undefined`, so it never gets here and mobile login test is failing.

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +const uploadAndSubmitDocument = async (page: Page, name: string) => {
`const uploadAndSubmitDocument = async (page: Page, name:  string = 'Atomic_number.pdf')`

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +const uploadAndSubmitDocument = async (page: Page, name: string) => {
`const uploadAndSubmitDocument = async (page: Page, name:  string = 'Atomic_number.pdf')`

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +    const fileName = name == null ? 'Atomic_number.pdf' : name;
this line can be removed.

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +    await page.setInputFiles('input[type="file"]', fileName);
`await page.setInputFiles('input[type="file"]', name);`

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +const selectUniversity = async (page: Page, name: string) => {
`const selectUniversity = async (page: Page, name: string = 'Universiteit Leiden') `

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +    const universityName = name == null ? 'Universiteit Leiden' : name;
this line is also not required

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +    await fillInInput(page, 'uploader-institution-input', universityName);
`await fillInInput(page, 'uploader-institution-input', name)`

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +    const courseName = name == null ? 'Organische Chemie' : name;
the same here as we can set default value in function parameter itslef

2022-08-24 09:49 UTC, mila-qa commented on pages/uploader.ts
> +    const categoryName = name == null ? 'Lecture notes' : name;
as above

2022-08-24 09:49 UTC, mila-qa commented on tests/uploader.spec.ts
> +const academicYear = '2022/2023';
it's not a point of the test to check different years in uploader, so also no need to keep it here. It should be passed as default parameter of function

2022-08-24 09:49 UTC, mila-qa commented on tests/uploader.spec.ts
> +const courseName = 'Organische chemie 1';
those lines are not needed here. They make code overloaded and less readable

2022-08-24 12:00 UTC, danielcastro-studocu commented on .env
> +USERNAME=user@loc.com
You are right, the env file should be used only for default data to be used when no specific data is specified.

2022-08-24 12:04 UTC, danielcastro-studocu commented on pages/home.ts
> +    if(isMobile){
Fixed in `login.spec.ts`.

2022-08-24 12:15 UTC, danielcastro-studocu commented on pages/uploader.ts
> +const uploadAndSubmitDocument = async (page: Page, name: string) => {
Fixed!

2022-08-24 12:15 UTC, danielcastro-studocu commented on pages/uploader.ts
> +    const fileName = name == null ? 'Atomic_number.pdf' : name;
Fixed!

2022-08-24 12:16 UTC, danielcastro-studocu commented on pages/uploader.ts
> +    await page.setInputFiles('input[type="file"]', fileName);
Fixed!

2022-08-24 12:16 UTC, danielcastro-studocu commented on pages/uploader.ts
> +    await page.setInputFiles('input[type="file"]', fileName);
Fixed!

2022-08-24 12:18 UTC, danielcastro-studocu commented on pages/uploader.ts
> +const selectUniversity = async (page: Page, name: string) => {
Fixed!

2022-08-24 12:19 UTC, danielcastro-studocu commented on pages/uploader.ts
> +    const universityName = name == null ? 'Universiteit Leiden' : name;
Removed!

2022-08-24 12:19 UTC, danielcastro-studocu commented on pages/uploader.ts
> +    await fillInInput(page, 'uploader-institution-input', universityName);
Fixed!

2022-08-24 12:20 UTC, danielcastro-studocu commented on pages/uploader.ts
> +    const courseName = name == null ? 'Organische Chemie' : name;
Fixed!

2022-08-24 12:21 UTC, danielcastro-studocu commented on pages/uploader.ts
> +    const categoryName = name == null ? 'Lecture notes' : name;
Fixed!

2022-08-25 08:23 UTC, danielcastro-studocu commented on tests/uploader.spec.ts
> +const courseName = 'Organische chemie 1';
Removed.

2022-08-25 15:34 UTC, prachistudocu approved these changes

2022-08-25 15:34 UTC, prachistudocu commented on pages/uploader.ts
> +const fillInDocumentDetails = async (page: Page, universityName: string = 'Universiteit Leiden', courseName: string = 'Organische Chemie', categoryName: string = 'Lecture notes', academicYear: string
Rather than Hard Coding the data, we can use data driven technique. Like .json file where we can store the data and use it tests

2022-08-25 15:55 UTC, danielcastro-studocu commented on pages/uploader.ts
> +const fillInDocumentDetails = async (page: Page, universityName: string = 'Universiteit Leiden', courseName: string = 'Organische Chemie', categoryName: string = 'Lecture notes', academicYear: string
The hard coded data in the methods will be used only for defining a default value to be used when no other value is received as an argument. If we adopt Gherkin the test data will be in the test scenarios within the features, or we can read any other data source for the tests.

2022-08-25 15:55 UTC, merged

2022-08-25 15:58 UTC, prachistudocu commented on pages/uploader.ts
> +const fillInDocumentDetails = async (page: Page, universityName: string = 'Universiteit Leiden', courseName: string = 'Organische Chemie', categoryName: string = 'Lecture notes', academicYear: string
Hmm ok. Makes sense, I have approved the PR