playwright-cucumber-integration
StuDocu/playwright-tests-sandbox pull request #4
Opened 2022-09-14 10:25 UTC by prachistudocu

This PR is to integrate cucumber with playwright

2022-09-21 13:52 UTC, danielcastro-studocu requested changes

2022-09-21 13:52 UTC, danielcastro-studocu commented on features/documentView.feature
> +    And I see in url "documentviewbooksolution"
My suggestion here is to replace the `And` keyword for `Then`, meaning that it’s the assertion step for the scenario. But I understand that this scenario is skipped with the tag ignore and the step definitions are not complete, so probably the scenario will be changed adding more steps when refactored.

2022-09-21 13:52 UTC, danielcastro-studocu commented on features/login.feature
> +    When I enter username and password
My suggestion here is to add an assertion step for the scenario with the keyword `Then`. Currently the step definition for this step `When` has a `waitForSelector` as an assertion after the login, which can be moved to the new step `Then`

2022-09-21 13:52 UTC, danielcastro-studocu commented on features/uploader.feature
> +    Given I upload a document with catgories
Since there’s a `Background` in this feature with a `Given` step, I’d consider this step as the first `When`.

2022-09-21 13:52 UTC, danielcastro-studocu commented on package.json
> +        "mobile": "npx playwright test --headed --project='mobile'",
The `mobile` and `mobile-headless` scripts are not running with an error `Error: No named projects are specified in the configuration file`. Moreover, by running playwright command instead of cucumber-js I believe that would not run the gherkin features. Can you check it besides fixing the execution for mobile?

2022-09-21 13:52 UTC, danielcastro-studocu commented on src/steps/general.steps.ts
> +});
Shouldn’t this file be named `general-steps`?

2022-09-21 13:52 UTC, danielcastro-studocu commented on src/steps/login-steps.ts
> +  page.waitForSelector('[data-test-selector="the-cookie-banner"]');
When I run this step the commands are “jamming”, so I added `await` before all of them to solve it.

2022-09-21 13:52 UTC, danielcastro-studocu commented on src/steps/login-steps.ts
> +  await page.waitForSelector('[data-test-selector="user-menu-button"]');
I’d move this to an assertion step `Then` to be added to the test scenario in the gherkin feature.

2022-09-21 13:52 UTC, danielcastro-studocu commented on src/support/config.ts
> +  headless: false,
Shouldn’t we add a script to `package.json` with an option for headless mode?

2022-09-21 13:52 UTC, danielcastro-studocu commented on src/support/config.ts
> +  BASE_URL: 'https://local.studocu.com/',
I think that these 3 lines are providing test data, not configuration. In the master branch there’s the `.env` file with such data but env is not the right approach for test data as well. In an upcoming refactoring we have to approach test data accordingly.

2022-09-21 13:52 UTC, danielcastro-studocu commented on src/steps/uploader.ts
> +Given('I upload a document with catgories', async function () {
Since we already have a `Given` step in the background of the gherkin feature, shouldn’t this be a `When` step?

2022-09-21 13:52 UTC, danielcastro-studocu commented on src/steps/uploader.ts
> +  await page.waitForSelector('[data-test-selector="the-cookie-banner"]');
These 2 lines regarding the cookies disclaimer are duplicates in the `login-steps` file, but I think they should be moved to the `Given` step in the `general-steps`.

2022-09-21 13:52 UTC, danielcastro-studocu commented on src/steps/uploader.ts
> +  /**const fillInDocumentDetails = async (page: Page, universityName: string = 'Universiteit Leiden', courseName: string = 'Organische Chemie', categoryName: string = 'Lecture notes', academicYear: s
Why is this code a comment now? Can you add a TO DO annotation with instructions about the refactoring needed?

2022-09-22 14:03 UTC, mila-qa commented on src/steps/documentView-steps.ts
> +  console.log(string);
here should be a real step right? could you add it please

2022-09-22 14:12 UTC, danielcastro-studocu commented on README.md
> +`BROWSER=firefox npm run test` or `BROWSER=firefox npx cucumber-js` runs all tests using Firefox
Webkit works fine for me, but I just realized that when I run Firefox there’s a certificate warning `SEC_ERROR_UNKNOWN_ISSUER` requiring the user to open Advanced options and to click on `Accept the Risk and Continue`.

2022-09-22 14:17 UTC, danielcastro-studocu commented on README.md
> +`npm run test <feature name>` or `npx cucumber-js <feature name>` run the single feature
It’s working with the relative path and the whole feature filename: `npm run test features/login.feature`

2022-09-22 14:20 UTC, danielcastro-studocu commented on features/login.feature
> +  Scenario: Login view event
I solved it by adding await before each of these lines, as mentioned in the comments in my review.

2022-09-22 14:22 UTC, danielcastro-studocu commented on README.md
> +## To run your tests
In the latest commit headful mode is defined as default, and I added a comment asking for a script on `package.json` to run it headless.

2022-09-22 14:23 UTC, danielcastro-studocu commented on src/steps/documentView-steps.ts
> +  console.log(string);
I think it’ll be covered in another user story/branch…

2022-09-22 14:32 UTC, prachistudocu commented on README.md
> +`BROWSER=firefox npm run test` or `BROWSER=firefox npx cucumber-js` runs all tests using Firefox
Thanks @danielcastro-studocu Yes, working for me as well. Should we add a step?

2022-09-22 14:33 UTC, prachistudocu commented on src/steps/uploader.ts
> +  /**const fillInDocumentDetails = async (page: Page, universityName: string = 'Universiteit Leiden', courseName: string = 'Organische Chemie', categoryName: string = 'Lecture notes', academicYear: s
I have actually added a cucumber refactored code now there

2022-09-22 14:34 UTC, prachistudocu commented on src/steps/uploader.ts
> +Given('I upload a document with catgories', async function () {
Amended

2022-09-22 14:34 UTC, prachistudocu commented on src/support/config.ts
> +  BASE_URL: 'https://local.studocu.com/',
Created a settings.ts file where I moved all the settings

2022-09-22 14:34 UTC, prachistudocu commented on package.json
> +        "mobile": "npx playwright test --headed --project='mobile'",
Working on it

2022-09-22 14:34 UTC, prachistudocu commented on features/uploader.feature
> +    Given I upload a document with catgories
done

2022-09-22 14:35 UTC, prachistudocu commented on features/login.feature
> +    When I enter username and password
Done

2022-09-22 14:35 UTC, prachistudocu commented on features/documentView.feature
> +    And I see in url "documentviewbooksolution"
Done

2022-09-22 14:35 UTC, prachistudocu commented on README.md
> +To stop the feature, you can add the `Then debug` step inside your feature. It will stop your debugger.
I have removed this because extra debug is not needed this can be done by `npm run debug`

2022-09-22 14:36 UTC, prachistudocu commented on README.md
> +`npm run test <feature name>` or `npx cucumber-js <feature name>` run the single feature
I will amend the README

2022-09-22 14:36 UTC, prachistudocu commented on src/support/common-hooks.ts
> +  switch (config.browser) {
working on it

2022-09-22 14:37 UTC, prachistudocu commented on src/steps/login-steps.ts
> +  page.click('[data-test-selector="header-login-button"]');
Do we need a scenario for rebranded variant as well which will have steps in general.steps

2022-09-22 14:39 UTC, prachistudocu commented on features/login.feature
> +  Scenario: Login view event
why your browser size is so small? Looks like it cannot see the headed login element

2022-09-22 15:00 UTC, prachistudocu commented on src/steps/documentView-steps.ts
> +  console.log(string);
Yes, there should be but this is just for demo and I am already adding my tests in current Sandbox repository however I can add couple of tests for visibility

2022-09-22 15:00 UTC, prachistudocu commented on README.md
> +## To run your tests
Working on it

2022-09-22 15:23 UTC, mila-qa commented on src/support/config.ts
> +    '--start-maximized',
the window is small, where tests are running. It'd be great to have it full size or/and the ability to set desired screen size

2022-09-22 15:25 UTC, danielcastro-studocu commented on src/support/config.ts
> +    '--start-maximized',
The arg ` '--start-maximized'` was supposed to maximize it… :/

2022-11-07 18:43 UTC, closed without merging