Chore/sc 37016 write registration tests
StuDocu/playwright-tests-sandbox pull request #5
Opened 2022-09-15 20:36 UTC by Tatiinzhee

Added registration happy pass test.

2022-09-21 15:31 UTC, mila-qa requested changes

2022-09-21 15:31 UTC, mila-qa commented on README.md
> + - npm install @faker-js/faker --save-dev
npm install will install dotenv and faker. No need to specify every package

2022-09-21 15:31 UTC, mila-qa commented on framework/pages/registration.ts
> +        await clickOnElement(page, 'content-sidebar-toggle');
If we declare selectors as constants, please let's not mix both approaches. Let's move selectors to constants as you did for Email etc field

2022-09-21 15:31 UTC, mila-qa commented on framework/pages/registration.ts
> +        await waitForVisible(page, 'choose-premium-button');
it'd be nice to make a few function here. For example fillInregistrationFileds(), submitRegistrationModal ... .They will be reusable in many other tests

2022-09-21 15:31 UTC, mila-qa commented on tests/registration.spec.ts
> +        await app().Registration().registerWithEmailAndActivate(page, firstname, lastmame, emailaddress, password);
to follow up previous comment. If the registration page will have a few functions we can use them here to extend a bit test with steps on how exactly registration is going on. Similar to regular test case steps

2022-09-23 13:58 UTC, danielcastro-studocu requested changes

2022-09-23 13:58 UTC, danielcastro-studocu commented on framework/pages/home.ts
>  const closeCookiesDisclaimer = async (page: Page) => {
`clickloginButton` was moved to `login` page, so it should be removed from here.

2022-09-23 13:58 UTC, danielcastro-studocu commented on package.json
> +    "@types/mocha": "^9.1.1",
What are we using `mocha` for in this project?

2022-09-23 13:58 UTC, danielcastro-studocu commented on package.json
> +    "test": "playwright-tests-sandbox specs/**/*.spec.ts -timeout 50000 --require @babel/register",
What’s the purpose of this script? I got `sh: playwright-tests-sandbox: command not found` error.

2022-09-23 13:58 UTC, danielcastro-studocu commented on tests/login.spec.ts
> +import {clickOnElement, fillInInput, waitForVisible} from '../framework/helpers/utils.ts';
`clickOnElement` and `fillInInput` are not used here, so you can remove them.

2022-09-23 13:58 UTC, danielcastro-studocu commented on tests/registration.spec.ts
> +const lastmame = faker.name.lastName();
Typo on `lastmame`.

2022-09-23 13:58 UTC, danielcastro-studocu commented on tests/registration.spec.ts
> +test.describe('Registration',  () => {
It’s a nice approach for grouping tests, but I think that different `specs` files will do that in the same way…

2022-09-23 13:58 UTC, danielcastro-studocu commented on README.md
> + - for creating page fields/selectors we age going to use 'data-test-selector' plese refer to util.ts file to find out
Typo on `we age going to use` and `plese refer to`.

2022-09-23 13:58 UTC, danielcastro-studocu commented on framework/pages/index.ts
> +import RegisrtationPage from './registration.ts';
Typo on `RegisrtationPage`.

2022-09-26 07:57 UTC, Tatiinzhee commented on README.md
> + - npm install @faker-js/faker --save-dev
Done

2022-09-26 07:58 UTC, Tatiinzhee commented on framework/pages/registration.ts
> +        await clickOnElement(page, 'content-sidebar-toggle');
Done

2022-09-26 07:58 UTC, Tatiinzhee commented on framework/pages/registration.ts
> +        await waitForVisible(page, 'choose-premium-button');
Done

2022-09-26 07:58 UTC, Tatiinzhee commented on framework/pages/home.ts
> +    await waitForVisible(page, 'the-cookie-banner');
done

2022-09-26 07:59 UTC, Tatiinzhee commented on framework/pages/login.ts
> +import {clickOnElement, fillInInput, waitForVisible} from "..framework/helpers/utils.ts";
Sure, thx.

2022-09-26 07:59 UTC, Tatiinzhee commented on framework/pages/login.ts
> +}
Login test will be refactored within my next pr.

2022-09-26 08:00 UTC, Tatiinzhee commented on tests/login.spec.ts
> +import {clickOnElement, fillInInput, waitForVisible} from '../framework/helpers/utils.ts';
the login test will refactored in my next pr, thx

2022-09-26 08:01 UTC, Tatiinzhee commented on tests/registration.spec.ts
> +test.describe('Registration',  () => {
sure, thx

2022-09-26 08:04 UTC, Tatiinzhee commented on framework/pages/activation.ts
> +const url = baseURL + local;
Let' keep by now, please, I still need to refactor the creating data.

2022-09-26 13:17 UTC, danielcastro-studocu requested changes
The only missing fix is the Typo on `RegisrtationPage`.

2022-09-26 15:57 UTC, danielcastro-studocu approved these changes

2022-09-27 11:54 UTC, mila-qa approved these changes
for now all good, suggested improvements are expected in upcoming PRs

2022-09-27 11:54 UTC, mila-qa commented on tests/registration.spec.ts
> +        await app().Registration().registerWithEmailAndActivate(page, firstname, lastmame, emailaddress, password);
as we agreed with @Tatiinzhee she will create steps for successful registration scenario in next PR

2022-09-27 11:54 UTC, mila-qa commented on framework/pages/registration.ts
> +        await waitForVisible(page, 'choose-premium-button');
dealing with home/landing page, accepting cookies etc will be moved into steps of test in related .spec.ts file. So we will have a ready test scenario in the spec file.
 Also registration and activation can be split even into smaller functions and they can be used during creating other test scenarios.

2022-09-27 12:25 UTC, merged