Added acquisitionStudentVerification and acquisitionLoggedIn tests
StuDocu/playwright-tests-sandbox pull request #6
Opened 2022-09-20 10:17 UTC by mila-qa

Fixed an issue with login test -> user name from env. Updated viewport in config as previous was too small. Enabled video records for failed tests

Please make sure that the local pipeline is running, while running acquisition tests. Follow instructions on [gitbook ](https://app.gitbook.com/o/-LnXMuXaeacEDOswz_RF/s/-Lo_KWmGXfkuWQKnXGl5/engineering/code/architecture/acquisition-process/acquisition-upload-locally)

2022-09-25 21:25 UTC, danielcastro-studocu requested changes

2022-09-27 19:02 UTC, mila-qa commented on pages/cookie-banner.ts
> +const submitCookieBanner = async (page: Page) => {
updated in [113a2a0](https://github.com/StuDocu/playwright-tests-sandbox/pull/6/commits/113a2a003425201d889d42215779b39d2cb64397)

2022-09-27 19:03 UTC, mila-qa commented on pages/header.ts
> +
also in [113a2a0](https://github.com/StuDocu/playwright-tests-sandbox/pull/6/commits/113a2a003425201d889d42215779b39d2cb64397)

2022-09-27 19:04 UTC, mila-qa commented on pages/uploader.ts
> +const acquisitionUploaderUrl = process.env.BASE_URL + process.env.BASE_LOCALIZATION + '/sell/upload?testFirstStepDAUploader=Control&testRebranding=Control';
updated

2022-09-27 19:05 UTC, mila-qa commented on pages/uploader.ts
> +    //we need unique selector on this step. 'student-verification-step' is a selector for a block, where user types e-mail
the locator above isn't unique, so we can't actually rely on it

2022-09-27 19:06 UTC, mila-qa commented on tests/login.spec.ts
> +const userName = process.env.USER_NAME;
Daniel, USERNAME is reserved system name. When I use USERNAME tests fails, because it takes the value from system info instead of .env file

2022-10-04 12:12 UTC, danielcastro-studocu approved these changes

2022-10-05 11:49 UTC, prachistudocu requested changes

2022-10-05 11:49 UTC, prachistudocu commented on framework/pages/uploader.ts
> +    await page.waitForTimeout(2500);
Instead of adding physical timeout we can make it dynamic saying `page.waitForSelector(uploaderInstitutionInput)`

2022-10-05 11:49 UTC, prachistudocu commented on framework/pages/uploader.ts
> +    await page.waitForTimeout(2500);
Same here as above

2022-10-05 11:49 UTC, prachistudocu commented on framework/pages/uploader.ts
> +    const verificationText = page.locator("//*[@data-test-selector='student-verification-step']//span");
This assignment is not been used anywhere, do we need it there?

2022-10-05 11:49 UTC, prachistudocu commented on framework/pages/uploader.ts
> +    //we need unique selector on this step. 'student-verification-step' is a selector for a block, where user types e-mail
Should we clean the code and not keep any commented code so that it looks nice and clean

2022-10-05 11:49 UTC, prachistudocu commented on playwright.config.ts
> +        viewport: { width: 1600, height: 980}
We at-lease need this viewport size to show the full screen. 
![Screenshot 2022-10-05 at 12 33 44](https://user-images.githubusercontent.com/100200967/194051411-a9dc9a2a-7404-4806-8787-f50377027384.png)

2022-10-05 11:49 UTC, prachistudocu commented on tests/acquisitionLoggedIn.spec.ts
> +    test.setTimeout(120000);
Do we want whole test to wait for that time? Can we use `await openLandingPage(page, {setTimeout: 120000});` instead?

2022-10-05 11:49 UTC, prachistudocu commented on tests/acquisitionStudentVerification.spec.ts
> +    test.setTimeout(120000);
Same here as above. Do we want whole test to wait for that time? Can we use await openAcquisitionUploader(page, {setTimeout: 120000}); instead?

2022-10-06 07:43 UTC, mila-qa commented on framework/pages/header.ts
> +const clickLoginButton = async (page: Page, isMobile) => {
it was already in main branch and it working well. I think we can keep it as an example of mobile implementation. Wdyt?

2022-10-06 10:23 UTC, mila-qa commented on framework/pages/uploader.ts
> +    await page.waitForTimeout(2500);
does it work for you? When i've replaced timeout with a suggestion the test fails exactly on this step
![image](https://user-images.githubusercontent.com/62964414/194289633-a9a28f1a-0214-4693-9b29-00bb748c98c7.png)

2022-10-06 10:24 UTC, mila-qa commented on framework/pages/uploader.ts
> +    await page.waitForTimeout(2500);
same as above

2022-10-06 12:05 UTC, mila-qa commented on framework/pages/landing.ts
>      await page.goto(url);
last master has both variants for Rebranded a/b test. I'm using in tests Control to simplify it for now

2022-10-06 12:08 UTC, mila-qa commented on framework/pages/uploader.ts
> +    //we need unique selector on this step. 'student-verification-step' is a selector for a block, where user types e-mail
I prefer to leave it here, otherwise, this check will be lost. It's a todo to update this place as soon as we will have selector

2022-10-06 12:11 UTC, mila-qa commented on playwright.config.ts
> +        viewport: { width: 1600, height: 980}
feel free to resize as you wish for a default value. The main goal of this change is to make resizing work, because the previous implementation wasn't correct

2022-10-06 12:13 UTC, mila-qa commented on framework/pages/header.ts
> +    await page.goto(uploaderURL + '&allowSingleUploads=true&testFirstStepDAUploader=Control');
updated in 5bfaa900941f61991482a3a4315837386b7a03b4

2022-10-07 13:54 UTC, Tatiinzhee approved these changes

2022-10-07 14:20 UTC, prachistudocu commented on framework/pages/uploader.ts
> +    const verificationText = page.locator("//*[@data-test-selector='student-verification-step']//span");
Ok lets go with it then

2022-10-07 14:20 UTC, prachistudocu commented on playwright.config.ts
> +        viewport: { width: 1600, height: 980}
sure

2022-10-07 14:21 UTC, prachistudocu commented on tests/acquisitionLoggedIn.spec.ts
> +    test.setTimeout(120000);
hmm weird! Let me take look and play with it. Lets keep as it is for now

2022-10-07 14:22 UTC, prachistudocu commented on framework/pages/uploader.ts
> +    //we need unique selector on this step. 'student-verification-step' is a selector for a block, where user types e-mail
We can add it from the commits later however keeping commented ToDo code should not be a problem then for the team too.

2022-10-07 14:23 UTC, prachistudocu commented on framework/pages/uploader.ts
> +    await page.waitForTimeout(2500);
let me check, we can go with what we have now

2022-10-07 14:23 UTC, prachistudocu commented on framework/pages/uploader.ts
> +    await page.waitForTimeout(2500);
Same as below

2022-10-07 14:24 UTC, prachistudocu approved these changes

2022-10-12 08:10 UTC, mila-qa commented on tests/acquisitionStudentVerification.spec.ts
> +
Tania, will do it in followed up PRs

2022-10-12 08:11 UTC, merged