Chore/sc 37019 document viewer automated tests
StuDocu/playwright-tests-sandbox pull request #7
Opened 2022-09-28 08:46 UTC by prachistudocu

Document Viewer Tests
- Comments on documents
- Document Viewer navigation and Save

2022-09-30 07:13 UTC, danielcastro-studocu commented
Should we really have over 500 files in this PR? I see that there’s a lot of node modules added, which I think should be ignored since they are added by NPM.

2022-09-30 16:18 UTC, danielcastro-studocu commented on tests/document-viewer/documentViewer.spec.ts
> +    var url = page.url();
Maybe this assertion should also be a function in Utils. WDYT?

2022-09-30 16:18 UTC, danielcastro-studocu commented on playwright-report/index.html
> +
I think this should not be pushed.

2022-10-03 09:41 UTC, prachistudocu commented on playwright-report/index.html
> +
This has been merged to Master from Tanya's PR

2022-10-04 10:29 UTC, mila-qa requested changes
first document viewer tests 🎉 Thanks for them!

2022-10-04 10:29 UTC, mila-qa commented on tests/document-viewer/comment.spec.ts
> +test('Reply on comment, Delete comment on a document/summary', async ({page, isMobile}) => {
Removing the reply to the comment is missing there. Original test ( `comment on a document/summary`) is checking deleting a comment and reply on comment. 
Could you please add deleteReply check here?

2022-10-04 10:29 UTC, mila-qa commented on tests/document-viewer/comment.spec.ts
> +   await authentication_modal.logout(page);
The purpose of this test to check, that logged out user can't comment documents.
No need here to login user. We can simply remove those lines

I'd suggest having just 2 steps for this test:
```
  document_viewer.openDocument();
  comment.notPossibleToLeaveCommentWithoutLogin();
```
where  `notPossibleToLeaveCommentWithoutLogin()`  is renamed `commentActionLoggedOutUser`. Just to add  more readability for test and clarify it purpose

2022-10-04 10:29 UTC, mila-qa commented on tests/document-viewer/documentViewer.spec.ts
> +    assert(url.includes('book-solution'), 'book-solution');
Here are a couple of options to check the correctness of URL with playwright build-in features:
 1.` await  page.waitForURL(<specific_expected_paramenters>)`
 2. `  await expect(page).toHaveURL(/\/book-solution/);` if we want to use pure assertions

2022-10-04 10:29 UTC, mila-qa commented on tests/document-viewer/documentViewer.spec.ts
> +const documentUrl = process.env.BASE_URL + process.env.BASE_LOCALIZATION + '/document/technische-universiteit-delft/vloeistofmechanica/book-solution-engineering-fluid-mechanics-clayton-t-crowe-barbar
`document/293381`

2022-10-04 10:29 UTC, mila-qa commented on tests/document-viewer/documentViewer.spec.ts
> +const saveDocumentUrl = process.env.BASE_URL + process.env.BASE_LOCALIZATION + '/document/technische-universiteit-delft/dynamica-2/samenvatting-van-de-gebruikte-formules-indeling-volgt-college-indeli
`document\8279`

2022-10-04 10:29 UTC, mila-qa commented on framework/pages/documentViewer/documentViewer.ts
> +    await page.locator(nextPageButton).isEnabled();
`nextPageButton ` should be disabled here, right? We use it for the test with 1 page 
'Cannot use page navigation on a 1 page document'

2022-10-04 10:29 UTC, mila-qa commented on tests/document-viewer/documentViewer.spec.ts
> +test('Save the document', async ({page, isMobile}) => {
Prachi, what feature file->scenario is that from gherkin repo?

2022-10-04 12:28 UTC, danielcastro-studocu approved these changes

2022-10-04 12:28 UTC, danielcastro-studocu commented on framework/pages/documentViewer/documentViewer.ts
> +    await page.locator(nextPageButton).isEnabled();
Or we need to use a document with more pages for this test.

2022-10-05 15:36 UTC, mila-qa requested changes
Please resolve all requested changes or reply on left comments

2022-10-05 15:38 UTC, mila-qa requested changes

2022-10-05 15:38 UTC, mila-qa commented on framework/pages/documentViewer/documentViewer.ts
> +const openDocument = async (page: Page, documentUrl: string) => {
for this function enough to have `  await page.goto(documentUrl);`
Please remove all others:
` await home_page.openLandingPage(page);
    await home_page.closeCookiesDisclaimer(page);
    await home_page.clickloginButton(page);
    await authentication_modal.loginWithEmail(page, userName, userPwd);`

2022-10-12 12:06 UTC, danielcastro-studocu commented on tests/registration.spec.ts
> +            Activation().activationWithTwoSteps(page, university, study);
It’s outdated according to Activation page. The lines removed above (in main) are the right one.

2022-10-13 15:00 UTC, danielcastro-studocu requested changes

2022-10-19 11:06 UTC, danielcastro-studocu approved these changes

2022-10-19 11:07 UTC, danielcastro-studocu commented on framework/pages/landing.ts
> +<<<<<<< HEAD
This merge tags should be removed:
`<<<<<<< HEAD`
`=======`
`>>>>>>> main`

2022-10-19 11:10 UTC, danielcastro-studocu commented on framework/helpers/utils.ts
> +    await element.waitFor({state: "visible"});
I’ve been reading the documentation for `waitFor` and the default timeout is 30000ms. Maybe we don’t need to set a default timeout of 10000 but keep the option of defining a custom timeout as `extraTimeout`.

2022-10-19 11:47 UTC, danielcastro-studocu approved these changes

2022-10-19 12:36 UTC, mila-qa requested changes

2022-10-19 12:36 UTC, mila-qa commented on framework/pages/documentViewer/documentViewer.ts
> +const saveDocumentButtonValue = '//*[@data-test-selector="save-document-button-8279"]';
```suggestion
const saveDocumentButtonValue = '(//*[contains(@data-test-selector, "save-document-button-")])[1]';
```
the Id in selector isn't static, to make selector more universal

2022-10-19 12:36 UTC, mila-qa commented on tests/document-viewer/documentViewer.spec.ts
> +    await expect(document_viewer.checkNextButtonState(page)).toBeFalsy();
```suggestion
    await expect(await document_viewer.checkPreviousButtonState(page)).toBeFalsy();
    await expect(await document_viewer.checkNextButtonState(page)).toBeFalsy();
```
otherwise `document_viewer.checkNextButtonState(page)` returns an empty object and test fails on those checks

2022-10-19 12:36 UTC, mila-qa commented on tests/document-viewer/documentViewer.spec.ts
> +    await authentication_modal.loginWithEmail(page, userName, userPwd);
I think those lines can be removed. We can straight forward go to document viewer and check the visibility of Next/Previous buttons

2022-10-19 12:36 UTC, mila-qa commented on framework/pages/documentViewer/comment.ts
> +    await clickOnElement(page, firstComment);
Prachi, do we need this click? A comment will be removed without this click, right?

2022-10-19 12:36 UTC, mila-qa commented on framework/pages/documentViewer/comment.ts
> +    await clickOnElement(page, replyComment);
same here, we can simply remove this line

2022-10-19 12:36 UTC, mila-qa commented on framework/pages/documentViewer/comment.ts
> +    await clickOnElement(page, confirmRemoveCommentButton);
typo here `confirmRemoveCommentButton`. This selector is for deleting comment, not reply.

```suggestion
   await clickOnElementCustomSelector(page, removeReplyOnCommentButton);
```

2022-10-19 12:36 UTC, mila-qa commented on framework/pages/documentViewer/comment.ts
> +const  commentReplyClose = 'comment-reply-close';
We need one more selector here for removing reply

`const removeReplyOnCommentButton = '//*[@data-test-selector="sidebar-comments-comment-0-replies-comment-0"]//*[@data-test-selector = "remove-comment-button"]';`

2022-10-19 12:36 UTC, mila-qa commented on tests/registration.spec.ts
> -        await expect (page.locator(institutionInput)).toHaveValue(university);
Any reason to remove those lines? It's a main branch version. Please revert changes in this file to align with main,

2022-10-19 12:39 UTC, mila-qa requested changes

2022-10-19 12:39 UTC, mila-qa commented on framework/pages/documentViewer/comment.ts
> +    await clickOnElement(page, removeCommentButton);
typo here `confirmRemoveCommentButton`. This selector is for deleting comment, not reply.

```suggestion
   await clickOnElementCustomSelector(page, removeReplyOnCommentButton);
```

2022-10-20 14:10 UTC, mila-qa approved these changes

2022-10-20 14:14 UTC, merged