Chore/sc 43521 refactoring registration flow tests
StuDocu/playwright-tests-sandbox pull request #8
Opened 2022-09-30 22:53 UTC by Tatiinzhee

1. Activation flow has been divided into two steps by now:
Activation Uni;
Activation Study;
2. Added extracting test info to define project name (to be able to distinguish flow by browser, if needed ).

2022-10-01 14:31 UTC, danielcastro-studocu requested changes

2022-10-01 14:31 UTC, danielcastro-studocu commented on framework/pages/activation.ts
> +    activationOfInstitution: async (page: Page, university: string, testInfo) => {
`testInfo` is not used here.

2022-10-01 14:31 UTC, danielcastro-studocu commented on package.json
> +    "@types/ua-parser-js": "^0.7.36"
Where is this lib used?

2022-10-01 18:45 UTC, Tatiinzhee commented on framework/pages/activation.ts
> +    activationOfInstitution: async (page: Page, university: string, testInfo) => {
Thank you Daniel.
Fixed

2022-10-02 14:34 UTC, danielcastro-studocu approved these changes

2022-10-05 12:10 UTC, prachistudocu requested changes

2022-10-05 12:10 UTC, prachistudocu commented on framework/pages/registration.ts
>  const RegistrationPage = {
It would be a good idea to create a function in utils.ts saying `clickAndFillInfo` which will include `page.click` and `page.fill` as they are using same parameters?

2022-10-05 12:10 UTC, prachistudocu commented on framework/pages/settings.ts
> +const passwordField = 'password-input';
Can we remove 
const firstnameField = 'first_name-input';
const lastmameField = 'last_name-input';
const emailaddressField = 'email-input';
const passwordField = 'password-input';
const studyInput = 'settings-page-study-input'; as they are being unused.

2022-10-05 12:10 UTC, prachistudocu commented on tests/registration.spec.ts
> +
Too much gap between import and const.
Remove unused imports
import { waitForVisible } from "../framework/helpers/utils.ts";
import { webkit } from '@playwright/test';

2022-10-05 12:10 UTC, prachistudocu commented on tests/registration.spec.ts
>  //todo refactor helper creating data
Remove commented code and unused const which is `const userSettingsPath = '/user/settings';` and `const userMenuButton = 'user-menu-button'
`

2022-10-05 12:10 UTC, prachistudocu commented on tests/registration.spec.ts
>  const baseURL = process.env.BASE_URL;
why aren't we using `const baseURL = process.env.BASE_URL + process.env.BASE_LOCALIZATION;

2022-10-07 14:44 UTC, Tatiinzhee commented on framework/pages/activation.ts
> +
done

2022-10-07 14:48 UTC, Tatiinzhee commented on framework/pages/landing.ts
>  const clickloginButton = async (page: Page, isMobile) => {
I still don't have the `header.ts` in master once. it there I move that function there

2022-10-07 14:49 UTC, Tatiinzhee commented on framework/pages/registration.ts
>  const RegistrationPage = {
Good idea, I'll implement it in the next PR's after login.

2022-10-07 14:49 UTC, prachistudocu commented on framework/pages/landing.ts
>  const clickloginButton = async (page: Page, isMobile) => {
cool

2022-10-07 14:50 UTC, Tatiinzhee commented on framework/pages/settings.ts
> +const passwordField = 'password-input';
I need them for the next PR's, could we please keep it?

2022-10-07 14:53 UTC, Tatiinzhee commented on tests/registration.spec.ts
> +
done

2022-10-07 14:56 UTC, Tatiinzhee commented on tests/registration.spec.ts
>  const baseURL = process.env.BASE_URL;
My way to make it shorter, should I change it?

2022-10-07 14:56 UTC, prachistudocu commented on framework/pages/registration.ts
>  const RegistrationPage = {
great

2022-10-07 14:57 UTC, prachistudocu commented on framework/pages/settings.ts
> +const passwordField = 'password-input';
ok

2022-10-07 14:58 UTC, prachistudocu commented on tests/registration.spec.ts
>  const baseURL = process.env.BASE_URL;
I think we can either keep it .env or just use the `const baseURL = process.env.BASE_URL + process.env.BASE_LOCALIZATION;` why repeat the task :)

2022-10-07 15:09 UTC, prachistudocu commented on tests/registration.spec.ts
>  //todo refactor helper creating data
Can we remove this?

2022-10-07 15:15 UTC, Tatiinzhee commented on tests/registration.spec.ts
>  //todo refactor helper creating data
Sure, done.

2022-10-07 15:32 UTC, merged