Chore/sc 37018 organic uploader tests
StuDocu/playwright-tests-sandbox pull request #9
Opened 2022-10-01 14:38 UTC by danielcastro-studocu

In this branch I’m adding more scenarios for the organic uploader, refactoring other pages to adopt the encapsulation approach suggested by @Tatiinzhee, moving functions to other pages according to the scope (like moving `clickloginButton` to `header.ts`).

2022-10-05 10:24 UTC, mila-qa reviewed
Solid and clean 💪. Thank you Daniel!

2022-10-05 10:24 UTC, mila-qa commented on framework/pages/registration.ts
> +        await app().LandingPage().openLandingPage(page);
```suggestion
        await app().Landing().openLandingPage(page);
```

2022-10-05 10:24 UTC, mila-qa commented on tests/uploader.spec.ts
> +    if(testInfo.project.name == 'webkit' || isMobile){
Daniel, just out of curiosity, what is wrong with webkit?

2022-10-06 13:10 UTC, danielcastro-studocu commented on tests/uploader.spec.ts
> +    if(testInfo.project.name == 'webkit' || isMobile){
Maybe it’s a specific situation that is happening only in my localenv, but even when I run it manually the university that is selected in the Search step is not pre-filled in the uploader details form. There’s also an error in the pre-filled Title which should be related to the filename.
I’m submitting the code as it is for now and planning to confirm if it’s a real bug in other local environments or as soon as my localenv is more stable and refactor this code as soon as I confirm that it’s working fine.

2022-10-12 13:02 UTC, mila-qa commented on framework/pages/uploader.ts
> +        await clickOnElement(page, submitDocumentsButton);
Last update: `Upload document and see premium days` seems to be an unstable test. It's not related to the local pipeline issue. After chatting with @danielcastro-studocu we figured out 2 moments:
  - clickOnElement() should have element visibility check;
  - setInputFiles() for a flow with logged-in user doesn't work stable and requires further investigation. Found temporarily workaround
  
 ```
  uploadAndSubmitDocument: async (page: Page, filename: string = 'Atomic_number.pdf') => {
        await page.waitForTimeout(3000);
        await page.setInputFiles(inputFile, filename);
        ...
        }
```

2022-10-13 15:08 UTC, mila-qa requested changes

2022-10-13 15:08 UTC, mila-qa commented on tests/uploader.spec.ts
> +    await app().Uploader().uploadAndSubmitDocument(page);
Test is failing on the below step in 90% of runs
`Running 1 test using 1 worker
  1) [chromium] › tests/uploader.spec.ts:20:6 › Upload document and see premium days ===============

    Test timeout of 120000ms exceeded.

    locator.waitFor: Target closed
    =========================== logs ===========================
    waiting for selector "[data-test-selector="uploaded-document-name"] >> nth=0" to be visible
    ============================================================

      29 |     await app().Uploader().openOrganicUploader(page);
      30 |     await app().Uploader().allowSingleUploads(page);
    > 31 |     await app().Uploader().uploadAndSubmitDocument(page);
         |     ^
`

2022-11-01 09:01 UTC, mila-qa commented on tests/uploader.spec.ts
> +    await app().Uploader().uploadAndSubmitDocument(page);
in  https://github.com/StuDocu/playwright-tests-sandbox/pull/9/commits/4f58a16972e075628f8ddea52059e451041ae478 and https://github.com/StuDocu/playwright-tests-sandbox/pull/9/commits/3b8d8fc94f9c3c2686be761237be773e468a29a9

2022-11-01 09:01 UTC, mila-qa approved these changes

2022-11-01 10:13 UTC, prachistudocu approved these changes

2022-11-01 17:16 UTC, merged